name: cryptolist
description: Cryptocurrency price list application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  decimal: ^0.3.5
  url_launcher: ^5.7.8
  charts_flutter: ^0.9.0
  bloc: ^6.1.0
  equatable: ^1.2.3
  rxdart: ^0.24.1
  flutter_bloc: ^6.1.1

flutter:
  uses-material-design: true
